### ISSUE TITLE
Update icon colors and header text for better visibility

### ISSUE THREAD

**Issue by madhurimarawat** [wecoded-dev/aquascript.github.io#5]
The icons currently blend with the background, making them difficult to distinguish. We need to update the icon colors globally for better visibility. Additionally, the header text next to the logo should match the icon color, and both should be styled with a darker version of the current gradient for consistency and better contrast.

---

### ☑ Goals:
- [x] Update the icon colors globally so they no longer blend with the background
- [x] Ensure the icon color contrasts well with the background and is clearly visible
- [x] Update the header text color next to the logo to match the icon color
- [x] Apply a **dark version of the current gradient** for both the icons and the header text to improve readability
- [x] Test for responsiveness and consistency across devices

---

### ☑ Example CSS Updates:

```css
/* Global icon color update */
.icon {
    color: #333333; /* Darker color to improve contrast */
    transition: color 0.3s ease-in-out;
}

/* Update header text color next to logo */
header .logo-text {
    color: #333333; /* Same as icon color */
    background: linear-gradient(135deg, #6cb2eb, #4f8bff); /* Dark gradient */
}

/* Optional: Update hover effect for icons */
.icon:hover {
    color: #1a1a1a; /* Slightly darker color on hover */
}
```
